# Generated by Django 2.2.1 on 2019-05-17 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifth_edition', '0002_abilityscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalAttack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('damage_type', models.CharField(choices=[('bl', 'Bludgeoning'), ('pi', 'Piercing'), ('sl', 'Slashing'), ('ac', 'Acid'), ('co', 'Cold'), ('fi', 'Fire'), ('fo', 'Force'), ('li', 'Lightning'), ('ne', 'Necrotic'), ('po', 'Poison'), ('ps', 'Psychic'), ('ra', 'Radiant'), ('th', 'Thunder')], max_length=2)),
                ('dice_type', models.CharField(choices=[('d4', 'd4'), ('d6', 'd6'), ('d8', 'd8'), ('d10', 'd10'), ('d12', 'd12')], max_length=3)),
                ('dice_count', models.IntegerField(default=1)),
                ('ability_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifth_edition.AbilityScore')),
            ],
        ),
    ]
