# Generated by Django 2.1.7 on 2019-05-17 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifth_edition', '0003_physicalattack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability_score', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fifth_edition.AbilityScore')),
            ],
            options={
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Spellcasting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spellcasting_ability', models.CharField(choices=[('Str', 'Strength'), ('Dex', 'Dexterity'), ('Con', 'Constitution'), ('Int', 'Intelligence'), ('Wis', 'Wisdom'), ('Cha', 'Charisma')], max_length=3)),
                ('ability_score', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fifth_edition.AbilityScore')),
            ],
            options={
                'verbose_name_plural': 'Spellcasting',
            },
        ),
    ]
