# Generated by Django 2.2 on 2019-05-19 00:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifth_edition', '0004_skills_spellcasting'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombatInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armor_class', models.IntegerField(default=10, verbose_name='Armor Class')),
                ('initiative', models.IntegerField(default=0, verbose_name='Initiative')),
                ('speed', models.IntegerField(default=0, verbose_name='Speed')),
                ('total_hit_points', models.PositiveIntegerField(default=1, verbose_name='Total Hit Points')),
                ('current_hit_points', models.PositiveIntegerField(default=1, verbose_name='Current Hit Points')),
                ('temporary_hit_points', models.PositiveIntegerField(default=0, verbose_name='Temporary Hit Points')),
                ('hit_dice_total', models.PositiveIntegerField(default=1, verbose_name='Total')),
                ('hit_dice', models.CharField(choices=[('d4', 'd4'), ('d6', 'd6'), ('d8', 'd8'), ('d10', 'd10'), ('d12', 'd12')], max_length=3, verbose_name='Hit Dice')),
                ('death_save_success', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)], verbose_name='Success')),
                ('death_save_failure', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)], verbose_name='Failure')),
            ],
        ),
    ]
