# Generated by Django 2.1.7 on 2019-05-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifth_edition', '0005_combatinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Background Name')),
                ('spec', models.CharField(blank=True, max_length=255, null=True, verbose_name='Specialization')),
                ('feature', models.CharField(blank=True, max_length=255, null=True, verbose_name='Feature')),
                ('alt_feature', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alternative Feature')),
                ('traits', models.CharField(blank=True, max_length=255, null=True, verbose_name='Traits')),
                ('ideals', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ideals')),
                ('bonds', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bonds')),
                ('flaws', models.CharField(blank=True, max_length=255, null=True, verbose_name='Flaws')),
                ('equipment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Granted Equipment')),
            ],
            options={
                'verbose_name_plural': 'Backgrounds',
            },
        ),
    ]
