# Generated by Django 2.1.7 on 2019-05-22 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifth_edition', '0006_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability_score', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ability_saves', to='fifth_edition.AbilityScore')),
            ],
            options={
                'verbose_name_plural': 'Saves',
            },
        ),
    ]
