# Generated by Django 3.0.2 on 2020-03-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifth_edition', '0007_save'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armortype', models.CharField(choices=[('Light', 'Light'), ('Medium', 'Medium'), ('Heavy', 'Heavy'), ('Shield', 'Shield')], max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('cost', models.IntegerField(help_text='Value in gold pieces.')),
                ('ac', models.IntegerField(help_text='Armor Class (AC) of armor.')),
                ('strength', models.IntegerField(help_text='Strength requirement to wear without Movement Speed (-10) penalty.')),
                ('stealth', models.CharField(choices=[('Disadvantage', 'Disadvantage'), ('None', 'None'), ('Advantage', 'Advantage')], max_length=32)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Value in pounds.', max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Armor',
            },
        ),
        migrations.AlterField(
            model_name='tool',
            name='set',
            field=models.CharField(choices=[("Artisan's Tools", "Artisan's Tools"), ('Gaming Set', 'Gaming Set'), ('General', 'General'), ('Musical Instrument', 'Musical Instrument')], max_length=32),
        ),
    ]
