# Generated by Django 3.0.2 on 2020-03-31 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifth_edition', '0008_armor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('physical_attack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifth_edition.PhysicalAttack')),
            ],
            options={
                'verbose_name_plural': 'Weapons',
            },
        ),
    ]
