# Generated by Django 3.0.2 on 2020-04-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifth_edition', '0010_gear'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='NPC Name')),
                ('level', models.IntegerField(default=1, verbose_name='Level')),
                ('npc_class', models.CharField(max_length=20, verbose_name='Class')),
                ('background', models.TextField(blank=True, null=True, verbose_name='Background')),
                ('race', models.CharField(choices=[('Dragonborn', 'Dragonborn'), ('Dwarf', 'Dwarf'), ('Elf', 'Elf'), ('Gnome', 'Gnome'), ('Half Elf', 'Half Elf'), ('Half Orc', 'Half Orc'), ('Halfling', 'Halfling'), ('Human', 'Human'), ('Tiefling', 'Tiefling')], max_length=20, verbose_name='Race')),
                ('alignment', models.CharField(max_length=50, verbose_name='Alignment')),
            ],
            options={
                'unique_together': {('name', 'npc_class', 'race')},
            },
        ),
    ]
