# Generated by Django 3.0.2 on 2020-04-02 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifth_edition', '0011_npc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('electrum_use', models.BooleanField(default=False)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='character_currency', to='fifth_edition.Character')),
            ],
            options={
                'verbose_name_plural': 'Currency',
            },
        ),
    ]
