# Generated by Django 3.0.2 on 2020-04-03 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifth_edition', '0012_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(help_text='Value in gold pieces.')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in pounds.', max_digits=10)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Other', 'Other'), ('Tool', 'Tool'), ('Armor', 'Armor'), ('Gear', 'Gear'), ('Weapon', 'Weapon')], max_length=32)),
                ('characters', models.ManyToManyField(to='fifth_edition.Character')),
                ('physical_attack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fifth_edition.PhysicalAttack')),
            ],
            options={
                'verbose_name_plural': 'Equipment',
            },
        ),
        migrations.CreateModel(
            name='PhysicalDefense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defensetype', models.CharField(choices=[('Light', 'Light'), ('Medium', 'Medium'), ('Heavy', 'Heavy'), ('Shield', 'Shield')], max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('ac', models.IntegerField(help_text='Armor Class (AC) of armor.')),
                ('strength', models.IntegerField(help_text='Strength requirement to wear without Movement Speed (-10) penalty.')),
                ('stealth', models.CharField(choices=[('Disadvantage', 'Disadvantage'), ('None', 'None'), ('Advantage', 'Advantage')], max_length=32)),
            ],
            options={
                'verbose_name_plural': 'PhysicalDefense',
            },
        ),
        migrations.DeleteModel(
            name='Armor',
        ),
        migrations.DeleteModel(
            name='Gear',
        ),
        migrations.DeleteModel(
            name='Weapon',
        ),
        migrations.AddField(
            model_name='equipment',
            name='physical_defense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fifth_edition.PhysicalDefense'),
        ),
    ]
