# Generated by Django 3.0.2 on 2020-04-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifth_edition', '0013_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='name',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='characters',
            field=models.ManyToManyField(blank=True, to='fifth_edition.Character'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='cost',
            field=models.PositiveIntegerField(help_text='Value in gold pieces.'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('Tool', 'Tool'), ('Gear', 'Gear'), ('Weapon', 'Weapon'), ('Other', 'Other'), ('Armor', 'Armor')], max_length=32),
        ),
    ]
