# Generated by Django 3.0.2 on 2020-04-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifth_edition', '0014_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='characters',
        ),
        migrations.AddField(
            model_name='character',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='fifth_edition.Equipment'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('Weapon', 'Weapon'), ('Tool', 'Tool'), ('Gear', 'Gear'), ('Armor', 'Armor'), ('Other', 'Other')], max_length=32),
        ),
    ]
