# Generated by Django 3.0.2 on 2020-04-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifth_edition', '0015_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalattack',
            name='properties',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physicalattack',
            name='weapon_type',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('Tool', 'Tool'), ('Weapon', 'Weapon'), ('Gear', 'Gear'), ('Other', 'Other'), ('Armor', 'Armor')], max_length=32),
        ),
        migrations.AlterField(
            model_name='physicalattack',
            name='damage_type',
            field=models.CharField(blank=True, choices=[('bl', 'Bludgeoning'), ('pi', 'Piercing'), ('sl', 'Slashing'), ('ac', 'Acid'), ('co', 'Cold'), ('fi', 'Fire'), ('fo', 'Force'), ('li', 'Lightning'), ('ne', 'Necrotic'), ('po', 'Poison'), ('ps', 'Psychic'), ('ra', 'Radiant'), ('th', 'Thunder')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='physicalattack',
            name='dice_count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='physicalattack',
            name='dice_type',
            field=models.CharField(blank=True, choices=[('1', '1'), ('d4', 'd4'), ('d6', 'd6'), ('d8', 'd8'), ('d10', 'd10'), ('d12', 'd12')], max_length=3, null=True),
        ),
    ]
