# Generated by Django 3.0.2 on 2020-04-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifth_edition', '0016_auto_20200402_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('Weapon', 'Weapon'), ('Armor', 'Armor'), ('Gear', 'Gear'), ('Tool', 'Tool'), ('Other', 'Other')], max_length=32),
        ),
    ]
