# Generated by Django 3.0.2 on 2020-04-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifth_edition', '0017_auto_20200405_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='spellcasting',
            name='spell_slots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('Tool', 'Tool'), ('Gear', 'Gear'), ('Armor', 'Armor'), ('Weapon', 'Weapon'), ('Other', 'Other')], max_length=32),
        ),
    ]
