# Generated by Django 3.0.2 on 2020-04-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifth_edition', '0018_auto_20200418_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casting_time', models.DurationField()),
                ('spell_range', models.PositiveIntegerField(default=0, help_text='Spell range in feet')),
                ('components', models.CharField(max_length=32)),
                ('duration', models.DurationField()),
                ('level', models.PositiveIntegerField(default=0, help_text='Spell level')),
                ('Name', models.CharField(max_length=32, unique=True)),
                ('Desc', models.CharField(max_length=280)),
                ('magic_school', models.CharField(choices=[('Abjuration', 'Abjuration'), ('Conjuration', 'Conjuration'), ('Divination', 'Divination'), ('Enchantment', 'Enchantment'), ('Evocation', 'Evocation'), ('Illusion', 'Illusion'), ('Necromancy', 'Necromancy'), ('Transmutation', 'Transmutation')], max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Spells',
            },
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('Tool', 'Tool'), ('Weapon', 'Weapon'), ('Armor', 'Armor'), ('Gear', 'Gear'), ('Other', 'Other')], max_length=32),
        ),
    ]
