# Generated by Django 3.0.2 on 2020-04-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifth_edition', '0019_auto_20200418_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='Desc',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='Name',
        ),
        migrations.AddField(
            model_name='spell',
            name='desc',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='name',
            field=models.CharField(default='name', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('Gear', 'Gear'), ('Tool', 'Tool'), ('Other', 'Other'), ('Armor', 'Armor'), ('Weapon', 'Weapon')], max_length=32),
        ),
    ]
