# Generated by Django 3.0.2 on 2020-04-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifth_edition', '0020_auto_20200418_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('Armor', 'Armor'), ('Weapon', 'Weapon'), ('Tool', 'Tool'), ('Gear', 'Gear'), ('Other', 'Other')], max_length=32),
        ),
    ]
