language: python
python:
  - "3.6"
install: 
  - pip install -r requirements.txt
script:
  - python manage.py test
services:
  - postgresql
before_script:
  - psql -c 'CREATE ROLE djangodnd LOGIN;' -U postgres
notifications:
  email:
    - tylerfrench@u.boisestate.edu
    - alexanderlakatos@u.boisestate.edu
  slack: capstone-dnd:710tlaIlWGLnHRLMM9e5OT5J